version: "3.7"
name: codelab-development

services:

  api_quarkus-dev:
    container_name: codelab_api_quarkus
    build:
      context: codelab-quarkus
      dockerfile: src/main/docker/Dockerfile.development
    image: quarkus/codelab-quarkus
    restart: unless-stopped
    ports:
      - "8070:8080"
    volumes:
      - ./codelab-quarkus:/app
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  db-dev:
    image: postgres:16
    container_name: codelab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codelab
      POSTGRES_PASSWORD: codelab
      POSTGRES_DB: codelab
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - codelab-dev

  db_ui-dev:
    image: dpage/pgadmin4
    container_name: codelab_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  webclient-dev:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./codelab-nextjs:/app

networks:
  codelab-dev:
    driver: bridge