version: "3.7"
name: codelab-development

services:

  api_quarkus-dev:
    container_name: codelab_api_quarkus
    build:
      context: codelab-quarkus
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - quarkus.http.host=0.0.0.0
    volumes:
      - ./codelab-quarkus:/app
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  api_exercices-dev:
    container_name: codelab_api_exercices
    build:
      context: codelab-exercices
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    volumes:
      - ./codelab-exercices:/app
    networks:
        - codelab-dev
    ports:
      - "8081:8080"
    environment:
      - quarkus.http.host=0.0.0.0
    depends_on:
      - api_exercices-rabbitmq

  api_exercices-rabbitmq:
    image: rabbitmq:3-alpine
    container_name: codelab_api_exercices_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    networks:
      - codelab-dev

  api_exercices-rabbitmq-ui:
    image: rabbitmq:3-management-alpine
    container_name: codelab_api_exercices_rabbitmq_ui
    restart: unless-stopped
    environment:
        RABBITMQ_DEFAULT_USER: codelab
        RABBITMQ_DEFAULT_PASS: codelab
    ports:
      - "15673:15672"
    networks:
      - codelab-dev

  db-dev:
    image: postgres:16
    container_name: codelab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codelab
      POSTGRES_PASSWORD: codelab
      POSTGRES_DB: codelab
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - codelab-dev

  db_ui-dev:
    image: dpage/pgadmin4
    container_name: codelab_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  webclient-dev:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./codelab-nextjs:/app
      - /codelab-nextjs/node_modules

networks:
  codelab-dev:
    driver: bridge