version: "3.7"
name: codelab

services:

  api_quarkus:
    container_name: codelab_api_quarkus
    build:
      context: codelab-quarkus
      dockerfile: src/main/docker/Dockerfile.native
    image: quarkus/codelab-quarkus
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./codelab-quarkus:/app
    networks:
      - codelab
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: codelab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codelab
      POSTGRES_PASSWORD: codelab
      POSTGRES_DB: codelab
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - codelab

  db_ui:
    image: dpage/pgadmin4
    container_name: codelab_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - codelab
    depends_on:
      - db

  webclient:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./codelab-nextjs:/app

networks:
  codelab:
    driver: bridge