version: "3.7"
name: codelab-development

services:

  api_exercices-dev:
    container_name: codelab_api_exercices
    build:
      context: codelab-exercices
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    volumes:
      - ./codelab-exercices:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - codelab-dev
    ports:
      - "8081:8080"
    environment:
      - quarkus.http.host=0.0.0.0
      - TESTCONTAINERS_RYUK_DISABLED=true
    depends_on:
      - api_exercices-mongodb

  api_exercices-mongodb:
    container_name: codelab_api_exercices_mongodb
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - codelab-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=codelab
      - MONGO_INITDB_ROOT_PASSWORD=codelab

  api_exercices-mongodb-ui:
    container_name: api_exercices-mongodb-ui
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8082:8081"
    networks:
      - codelab-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=codelab
      - ME_CONFIG_MONGODB_ADMINPASSWORD=codelab
      - ME_CONFIG_MONGODB_SERVER=api_exercices-mongodb
    depends_on:
      - api_exercices-mongodb

  webclient-dev:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./codelab-nextjs:/app
      - /codelab-nextjs/node_modules

networks:
  codelab-dev:
    driver: bridge