version: "3.7"
name: codelab-development

services:

  api_auth-dev:
    container_name: codelab_auth_api
    build:
      context: codelab-auth
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./codelab-auth:/app
    networks:
      - codelab-dev
    depends_on:
      - db_auth-dev

  db_auth-dev:
    image: postgres:16
    container_name: codelab_auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codelab-auth
      POSTGRES_PASSWORD: codelab-auth
      POSTGRES_DB: codelab-auth
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - codelab-dev

  adminer-auth:
    image: adminer
    container_name: codelab_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
        - codelab-dev

  webclient-dev:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./codelab-nextjs:/app
      - /codelab-nextjs/node_modules

networks:
  codelab-dev:
    driver: bridge