version: "3.7"
name: codelab-development

services:

  api_quarkus-dev:
    container_name: codelab_api_quarkus
    build:
      context: codelab-quarkus
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - quarkus.http.host=0.0.0.0
    volumes:
      - ./codelab-quarkus:/app
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  api_exercices-dev:
    container_name: codelab_api_exercices
    build:
      context: codelab-exercices
      dockerfile: src/main/docker/Dockerfile.development
    restart: unless-stopped
    volumes:
      - ./codelab-exercices:/app
    networks:
      - codelab-dev
    ports:
      - "8081:8080"
    environment:
      - quarkus.http.host=0.0.0.0
    depends_on:
      - api_exercices-mongodb

  api_exercices-mongodb:
    container_name: codelab_api_exercices_mongodb
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - codelab-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=codelab
      - MONGO_INITDB_ROOT_PASSWORD=codelab

  api_exercices-mongodb-ui:
    container_name: api_exercices-mongodb-ui
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8082:8081"
    networks:
      - codelab-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=codelab
      - ME_CONFIG_MONGODB_ADMINPASSWORD=codelab
      - ME_CONFIG_MONGODB_SERVER=api_exercices-mongodb
    depends_on:
      - api_exercices-mongodb

  db-dev:
    image: postgres:16
    container_name: codelab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codelab
      POSTGRES_PASSWORD: codelab
      POSTGRES_DB: codelab
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - codelab-dev

  db_ui-dev:
    image: dpage/pgadmin4
    container_name: codelab_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - codelab-dev
    depends_on:
      - db-dev

  webclient-dev:
    container_name: codelab_webclient
    build:
      context: ./codelab-nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./codelab-nextjs:/app
      - /codelab-nextjs/node_modules

networks:
  codelab-dev:
    driver: bridge