version: "3.7"

services:
  placeholder:
    image: placeholder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - codelab

networks:
  codelab:
    driver: bridge