@startuml

!define UI_COLOR LightBlue
!define API_COLOR Yellow
!define CACHE_COLOR DarkOrange
!define CICD_COLOR PaleGreen
!define BROKER_COLOR Gray

title __Plateforme d'apprentissage du code__\n
footer © 2023 - Codelab - Alexis GRIDEL, Samuel POMIN, Théo PELLIZZARI, Vincent BRACH, Maxime CARLIER

component "Interface utilisateur" as UI #UI_COLOR {
  component [NextJS] as nextjs
  component [React] as react
  component [Monaco Editor] as monaco
}

component "Backend" as API #API_COLOR {
  component [OpenAPI] as openapi
  component [REST API] as rest
  component [Services] as services
  database [MongoDB] as mongo
  database [PostgreSQL] as sql
}

node "Cache" as cache #CACHE_COLOR {
  component [Redis] as redis
}

component "CI/CD" as cicd #CICD_COLOR {
  component [GitHub] as github
  component [Jenkins] as jenkins
}

component "Message Broker" as broker #BROKER_COLOR {
  component [RabbitMQ] as rabbitmq
}

UI -[#Blue]> rest
rest -[#FF9900]> services
services -[#FF9900]> mongo
services -[#FF9900]> sql
rest -[#FF9900]> openapi
UI -[#Green]> github : push
github -[#Green]> jenkins : deploy
cache -[#99FF99]-> services
services -[#DarkGrey]-> rabbitmq : asynchronous\nmessaging

@enduml
