@startuml

title Diagramme de cas d'utilisation
left to right direction
skinparam actorStyle awesome

:Visiteur: as Guest
:Utilisateur: as User
:Administrateur: as Admin

package Connexion {
    (S'identifier) as Signin
    (Créer un compte) as Signup
    (Se déconnecter) as Signout
}

package Profil {
    (Consulter son profil) as SeeProfile
    (Gérer son profil) as ManageProfile
    (Consulter les cours favoris) as SeeFavoriteCourses
    (Voir les cours terminés) as SeeFinishedCourses
}

package Cours {
    (Rechercher des cours) as SearchCourses
    (Consulter le détail d'un cours) as SeeCourseContent
    (Commencer un cours) as StartCourse
    (Ajouter un cours aux favoris) as AddCourseToFavorites
    (Finir un cours) as FinishCourse
    (Donner une note) as GiveRating
}

package Exercice {
    (Faire un exercice) as DoExercise
    (Créer un exercice) as CreateExercise
    (Finir un exercice) as FinishExercice
}

package Administration {
    (Gérer les utilisateurs) as ManageUsers
    (Gérer les cours) as ManageCourses
    (Gérer les exercices) as ManageExercises
}

package Experience {
    (Gagner de l'expérience) as GainExperience
    (Gagner un niveau) as GainLevel
    (Gagner des badges) as GainBadges
    (Voir son expérience) as SeeExperience
    (Voir son niveau) as SeeLevel
}


Signin <.. User
Signup <.. Signin
Signin <.. Signout

SeeProfile <.. ManageProfile
SeeProfile <.. SeeFavoriteCourses
SeeProfile <.. SeeFinishedCourses

SearchCourses <.. SeeCourseContent
SeeCourseContent <.. AddCourseToFavorites
SeeCourseContent <.. StartCourse
StartCourse <.. FinishCourse
FinishCourse <.. GiveRating

DoExercise <.. FinishExercice
FinishExercice <.. FinishCourse

GainExperience <.. GainLevel
GainLevel <.. GainBadges
GainExperience <.. SeeExperience
GainLevel <.. SeeLevel



Guest --> Signin
Guest --> Signup
Guest --> SearchCourses


User --|> Guest


User --> SeeProfile
User --> GainExperience

User --> CreateExercise
User --> DoExercise


Admin --|> User

Admin --> ManageCourses
Admin --> ManageExercises
Admin --> ManageUsers


@enduml